# language: php

filter:
  paths:
    - src/*
    - tests/*

coding_style:
  php:
    upper_lower_casing:
      keywords:
        general: lower
      constants:
        true_false_null: lower

checks:
  php:
    code_rating: true
    duplication: true
    uppercase_constants: true
    properties_in_camelcaps: true
    prefer_while_loop_over_for_loop: true
    parameters_in_camelcaps: true
    optional_parameters_at_the_end: true
    no_short_variable_names:
      minimum: '3'
    no_short_method_names:
      minimum: '3'
    no_goto: true
    newline_at_end_of_file: true
    more_specific_types_in_doc_comments: true
    line_length:
      max_length: '120'
    function_in_camel_caps: true
    encourage_single_quotes: true
    encourage_postdec_operator: true
    classes_in_camel_caps: true
    avoid_perl_style_comments: true
    avoid_multiple_statements_on_same_line: true
    parameter_doc_comments: true
    use_self_instead_of_fqcn: true
    simplify_boolean_return: true
    avoid_fixme_comments: true
    return_doc_comments: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true

tools:
  php_code_coverage: false
  php_code_sniffer:
    enabled: true
    config:
      standard: 'PSR2'
    filter:
      paths: [src, tests]

  php_cpd:
    enabled: true
    excluded_dirs: [dist, tests, vendor]
  php_mess_detector:
    enabled: true
  php_loc:
    enabled: true
    excluded_dirs: [dist, tests, vendor]
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true

before_commands:
  - 'composer self-update'
  - 'composer install --no-interaction --prefer-source'
